# Generated by Django 4.0.5 on 2022-06-07 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='National ID'),
        ),
        migrations.AlterField(
            model_name='courier',
            name='income',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='extraincome',
            name='courier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salary.courier'),
        ),
        migrations.CreateModel(
            name='WeeklyIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saturday', models.DateTimeField()),
                ('amount', models.FloatField()),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salary.courier')),
            ],
        ),
        migrations.CreateModel(
            name='DailyIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('amount', models.FloatField()),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salary.courier')),
            ],
        ),
    ]
