# Generated by Django 4.0.5 on 2022-06-08 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0003_alter_courier_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penalty',
            name='courier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salary.courier'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='customer_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salary.customer'),
        ),
    ]
